# Compare thigh, as opposed to to whole body based, segmentation to ground truth

In [1]:
# libraries
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.colors import ListedColormap
from ipywidgets import interact, fixed
from IPython.display import clear_output
import SimpleITK as sitk

In [2]:
!pwd

/c/Projects/dissector/eval_notebooks/myosegmenTUM

In [5]:
results_r_gracilis = []
for file in os.listdir(os.path.join("..","MuscleMap_thigh_segs")):
    print(file)
    if file[0] == 'H':
        gt_name = file[:7]+"/SegmentationMasks/combined_gt_stack"+ file[-13] +".mha"
    else:
        gt_name = file[:6]+"/SegmentationMasks/combined_gt_stack"+ file[-13] +".mha"
        
    print(gt_name)
    segment_image = sitk.ReadImage(os.path.join("..","MuscleMap_thigh_segs",file))
    new_segment_array = sitk.GetArrayFromImage(segment_image)
    gt_image= sitk.ReadImage(gt_name)
    segment_image.CopyInformation(gt_image)
    # actually lower
    #results = []
    gt = sitk.Cast(gt_image ==  5, sitk.sitkUInt8)
    pred = sitk.Cast(segment_image == 12, sitk.sitkUInt8)
    
    gt_arr = sitk.GetArrayFromImage(gt)
    pred_arr = sitk.GetArrayFromImage(pred)
    
    print("GT voxels:", np.sum(gt_arr))
    print("Pred voxels:", np.sum(pred_arr))
    dice_filter = sitk.LabelOverlapMeasuresImageFilter()
    dice_filter.Execute(gt, pred)
    
    right_grac_dice_lower = dice_filter.GetDiceCoefficient()
    right_JaccardCoeffi  = dice_filter.GetJaccardCoefficient()
    right_VolumeSimilar = dice_filter.GetVolumeSimilarity()
    right_FalseNegative = dice_filter.GetFalseNegativeError()
    right_FalsePositive  = dice_filter.GetFalsePositiveError()
    #print("Right gracilis lower dice:", right_grac_dice_lower)
    hd_filter = sitk.HausdorffDistanceImageFilter()
    hd_filter.Execute(gt, pred)
    
    right_grac_hd_lower = hd_filter.GetHausdorffDistance()
    #print("Right gracilis lower Hausdorff distance:", right_grac_hd_lower)
    results_r_gracilis.append({
            "image": gt_name,
            "pred_label": file,
            "R_gracilis_lower_dice:": right_grac_dice_lower,
            "R_gracilis_lower_Hausdorff:": right_grac_hd_lower,
            "R_gracilis_jaccard":right_JaccardCoeffi,
            "R_gracilis_volume_similarity":right_VolumeSimilar,
            "R_gracilis_falseNegative":right_FalseNegative,
            "R_gracilis_falsePostivie":right_FalsePositive,
        })
df_r_gracilis = pd.DataFrame(results_r_gracilis)
df_r_gracilis#.to_csv('../MuscleMap_results_WB/df_r_gracilis.csv')

HV001_1_FATFRACTION_stack1_dseg.nii.gz
HV001_1/SegmentationMasks/combined_gt_stack1.mha
GT voxels: 15952
Pred voxels: 16362
HV001_1_FATFRACTION_stack2_dseg.nii.gz
HV001_1/SegmentationMasks/combined_gt_stack2.mha
GT voxels: 15923
Pred voxels: 19383
HV001_2_FATFRACTION_stack1_dseg.nii.gz
HV001_2/SegmentationMasks/combined_gt_stack1.mha
GT voxels: 16173
Pred voxels: 17564
HV001_2_FATFRACTION_stack2_dseg.nii.gz
HV001_2/SegmentationMasks/combined_gt_stack2.mha
GT voxels: 14708
Pred voxels: 18977
HV001_3_FATFRACTION_stack1_dseg.nii.gz
HV001_3/SegmentationMasks/combined_gt_stack1.mha
GT voxels: 17379
Pred voxels: 17211
HV001_3_FATFRACTION_stack2_dseg.nii.gz
HV001_3/SegmentationMasks/combined_gt_stack2.mha
GT voxels: 16412
Pred voxels: 18636

,image,pred_label,R_gracilis_lower_dice:,R_gracilis_lower_Hausdorff:,R_gracilis_jaccard,R_gracilis_volume_similarity,R_gracilis_falseNegative,R_gracilis_falsePostivie
0,HV001_1/SegmentationMasks/combined_gt_stack1.mha,HV001_1_FATFRACTION_stack1_dseg.nii.gz,0.875596,7.280110,0.778720,-0.025376,0.135375,0.000062
1,HV001_1/SegmentationMasks/combined_gt_stack2.mha,HV001_1_FATFRACTION_stack2_dseg.nii.gz,0.870277,5.656854,0.770345,-0.196001,0.207398,0.000027
2,HV001_2/SegmentationMasks/combined_gt_stack1.mha,HV001_2_FATFRACTION_stack1_dseg.nii.gz,0.867534,8.062258,0.766058,-0.082461,0.166818,0.000052
3,HV001_2/SegmentationMasks/combined_gt_stack2.mha,HV001_2_FATFRACTION_stack2_dseg.nii.gz,0.851596,8.246211,0.741547,-0.253466,0.244190,0.000018
4,HV001_3/SegmentationMasks/combined_gt_stack1.mha,HV001_3_FATFRACTION_stack1_dseg.nii.gz,0.876265,8.062258,0.779779,0.009714,0.119458,0.000076
5,HV001_3/SegmentationMasks/combined_gt_stack2.mha,HV001_3_FATFRACTION_stack2_dseg.nii.gz,0.894545,5.744563,0.809209,-0.126912,0.158832,0.000036

In [ ]:
!pwd

In [6]:
old = pd.read_csv('../MuscleMap_results_WB/df_r_gracilis.csv')
old

,Unnamed: 0,image,pred_label,R_gracilis_lower_dice:,R_gracilis_lower_Hausdorff:,R_gracilis_jaccard,R_gracilis_volume_similarity,R_gracilis_falseNegative,R_gracilis_falsePostivie
0,0,HV001_1/SegmentationMasks/combined_gt_stack1.mha,HV001_1_FATFRACTION_stack1_dseg.nii.gz,0.864141,11.045361,0.760782,-0.070575,0.165313,0.000057
1,1,HV001_1/SegmentationMasks/combined_gt_stack2.mha,HV001_1_FATFRACTION_stack2_dseg.nii.gz,0.880848,16.000000,0.787067,-0.020081,0.127908,0.000086
2,2,HV001_2/SegmentationMasks/combined_gt_stack1.mha,HV001_2_FATFRACTION_stack1_dseg.nii.gz,0.844484,14.866069,0.730828,-0.096734,0.194477,0.000062
3,3,HV001_2/SegmentationMasks/combined_gt_stack2.mha,HV001_2_FATFRACTION_stack2_dseg.nii.gz,0.867442,20.000000,0.765913,-0.084335,0.167656,0.000068
4,4,HV001_3/SegmentationMasks/combined_gt_stack1.mha,HV001_3_FATFRACTION_stack1_dseg.nii.gz,0.864027,9.055385,0.760606,-0.052282,0.157984,0.000067
5,5,HV001_3/SegmentationMasks/combined_gt_stack2.mha,HV001_3_FATFRACTION_stack2_dseg.nii.gz,0.889236,16.031220,0.800562,0.048875,0.088489,0.000106
6,6,HV002_1/SegmentationMasks/combined_gt_stack1.mha,HV002_1_FATFRACTION_stack1_dseg.nii.gz,0.836608,20.248457,0.719111,0.068192,0.133861,0.000171
7,7,HV002_1/SegmentationMasks/combined_gt_stack2.mha,HV002_1_FATFRACTION_stack2_dseg.nii.gz,0.873970,24.000000,0.776152,-0.039984,0.143160,0.000077
8,8,HV002_2/SegmentationMasks/combined_gt_stack1.mha,HV002_2_FATFRACTION_stack1_dseg.nii.gz,0.855348,18.681542,0.747257,0.044249,0.125299,0.000139
9,9,HV002_2/SegmentationMasks/combined_gt_stack2.mha,HV002_2_FATFRACTION_stack2_dseg.nii.gz,0.868235,24.041631,0.767151,0.115447,0.078578,0.000160
10,10,HV002_3/SegmentationMasks/combined_gt_stack1.mha,HV002_3_FATFRACTION_stack1_dseg.nii.gz,0.840097,17.549929,0.724282,-0.100430,0.200071,0.000090
11,11,HV002_3/SegmentationMasks/combined_gt_stack2.mha,HV002_3_FATFRACTION_stack2_dseg.nii.gz,0.874371,24.103942,0.776784,0.057247,0.099864,0.000120
12,12,HV003_1/SegmentationMasks/combined_gt_stack1.mha,HV003_1_FATFRACTION_stack1_dseg.nii.gz,0.853742,22.360680,0.744807,0.128707,0.087538,0.000176
13,13,HV003_1/SegmentationMasks/combined_gt_stack2.mha,HV003_1_FATFRACTION_stack2_dseg.nii.gz,0.887382,24.083189,0.797562,0.123799,0.054065,0.000153
14,14,HV003_2/SegmentationMasks/combined_gt_stack1.mha,HV003_2_FATFRACTION_stack1_dseg.nii.gz,0.866999,12.165525,0.765224,0.141577,0.066952,0.000180
15,15,HV003_2/SegmentationMasks/combined_gt_stack2.mha,HV003_2_FATFRACTION_stack2_dseg.nii.gz,0.897668,20.099751,0.814335,0.129938,0.039960,0.000148
16,16,HV003_3/SegmentationMasks/combined_gt_stack1.mha,HV003_3_FATFRACTION_stack1_dseg.nii.gz,0.853384,10.049876,0.744264,0.173300,0.065655,0.000201
17,17,HV003_3/SegmentationMasks/combined_gt_stack2.mha,HV003_3_FATFRACTION_stack2_dseg.nii.gz,0.884630,28.017851,0.793127,0.144913,0.046266,0.000171
18,18,HV004_1/SegmentationMasks/combined_gt_stack1.mha,HV004_1_FATFRACTION_stack1_dseg.nii.gz,0.873810,10.677078,0.775900,0.074721,0.092277,0.000075
19,19,HV004_1/SegmentationMasks/combined_gt_stack2.mha,HV004_1_FATFRACTION_stack2_dseg.nii.gz,0.893368,20.099751,0.807286,0.023139,0.096175,0.000049
20,20,HV005_1/SegmentationMasks/combined_gt_stack1.mha,HV005_1_FATFRACTION_stack1_dseg.nii.gz,0.854804,7.071068,0.746426,-0.005071,0.147358,0.000092
21,21,HV005_1/SegmentationMasks/combined_gt_stack2.mha,HV005_1_FATFRACTION_stack2_dseg.nii.gz,0.867030,40.311289,0.765272,-0.028241,0.145042,0.000073
22,22,HV006_1/SegmentationMasks/combined_gt_stack1.mha,HV006_1_FATFRACTION_stack1_dseg.nii.gz,0.875903,9.219544,0.779206,0.005789,0.121554,0.000083
23,23,HV006_1/SegmentationMasks/combined_gt_stack2.mha,HV006_1_FATFRACTION_stack2_dseg.nii.gz,0.890950,12.369317,0.803346,0.007649,0.105629,0.000107
24,24,HV007_1/SegmentationMasks/combined_gt_stack1.mha,HV007_1_FATFRACTION_stack1_dseg.nii.gz,0.882372,10.816654,0.789504,-0.013416,0.123508,0.000100
25,25,HV007_1/SegmentationMasks/combined_gt_stack2.mha,HV007_1_FATFRACTION_stack2_dseg.nii.gz,0.861855,24.413111,0.757245,0.032525,0.123897,0.000132
26,26,HV008_1/SegmentationMasks/combined_gt_stack1.mha,HV008_1_FATFRACTION_stack1_dseg.nii.gz,0.888543,5.830952,0.799440,0.045309,0.090861,0.000106
27,27,HV008_1/SegmentationMasks/combined_gt_stack2.mha,HV008_1_FATFRACTION_stack2_dseg.nii.gz,0.884022,20.248457,0.792149,0.025421,0.104597,0.000072
28,28,HV009_1/SegmentationMasks/combined_gt_stack1.mha,HV009_1_FATFRACTION_stack1_dseg.nii.gz,0.823265,29.966648,0.699618,-0.026302,0.187421,0.000092
29,29,HV009_1/SegmentationMasks/combined_gt_stack2.mha,HV009_1_FATFRACTION_stack2_dseg.nii.gz,0.863967,7.810250,0.760512,-0.011369,0.140917,0.000073
30,30,HV010_1/SegmentationMasks/combined_gt_stack1.mha,HV010_1_FATFRACTION_stack1_dseg.nii.gz,0.870252,12.041595,0.770306,0.008880,0.125867,0.000042
31,31,HV010_1/SegmentationMasks/combined_gt_stack2.mha,HV010_1_FATFRACTION_stack2_dseg.nii.gz,0.853489,28.017851,0.744423,-0.021150,0.155442,0.000074
32,32,HV011_1/SegmentationMasks/combined_gt_stack1.mha,HV011_1_FATFRACTION_stack1_dseg.nii.gz,0.860814,12.041595,0.755640,0.030472,0.125867,0.000049
33,33,HV011_1/SegmentationMasks/combined_gt_stack2.mha,HV011_1_FATFRACTION_stack2_dseg.nii.gz,0.838202,24.020824,0.721470,-0.009888,0.165921,0.000086
34,34,HV012_1/SegmentationMasks/combined_gt_stack1.mha,HV012_1_FATFRACTION_stack1_dseg.nii.gz,0.524480,16.763055,0.355454,-0.771114,0.621466,0.000015
35,35,HV012_1/SegmentationMasks/combined_gt_stack2.mha,HV012_1_FATFRACTION_stack2_dseg.nii.gz,0.564573,12.083046,0.393314,-0.848620,0.603616,0.000006
36,36,HV013_1/SegmentationMasks/combined_gt_stack1.mha,HV013_1_FATFRACTION_stack1_dseg.nii.gz,0.752900,16.763055,0.603721,-0.422165,0.378324,0.000021
37,37,HV013_1/SegmentationMasks/combined_gt_stack2.mha,HV013_1_FATFRACTION_stack2_dseg.nii.gz,0.813065,12.000000,0.685012,-0.274272,0.284989,0.000052
38,38,HV014_1/SegmentationMasks/combined_gt_stack1.mha,HV014_1_FATFRACTION_stack1_dseg.nii.gz,0.587609,20.493902,0.416039,-0.807580,0.581412,0.000006
39,39,HV014_1/SegmentationMasks/combined_gt_stack2.mha,HV014_1_FATFRACTION_stack2_dseg.nii.gz,0.550059,32.526912,0.379367,-0.721256,0.595731,0.000053
40,40,HV015_1/SegmentationMasks/combined_gt_stack1.mha,HV015_1_FATFRACTION_stack1_dseg.nii.gz,0.667257,12.649111,0.500664,-0.610607,0.488811,0.000018
41,41,HV015_1/SegmentationMasks/combined_gt_stack2.mha,HV015_1_FATFRACTION_stack2_dseg.nii.gz,0.711508,12.000000,0.552202,-0.411262,0.409846,0.000097
42,42,P001_1/SegmentationMasks/combined_gt_stack1.mha,P001_1_FATFRACTION_stack1_dseg.nii.gz,0.814462,13.152946,0.686998,-0.265674,0.281042,0.000105
43,43,P001_1/SegmentationMasks/combined_gt_stack2.mha,P001_1_FATFRACTION_stack2_dseg.nii.gz,0.874351,4.582576,0.776752,-0.096615,0.165940,0.000158
44,44,P001_1/SegmentationMasks/combined_gt_stack3.mha,P001_1_FATFRACTION_stack3_dseg.nii.gz,0.615238,5.385165,0.444291,-0.736813,0.550398,0.000008
45,45,P002_1/SegmentationMasks/combined_gt_stack1.mha,P002_1_FATFRACTION_stack1_dseg.nii.gz,0.730533,4.000000,0.575465,-0.528551,0.422172,0.000003
46,46,P002_1/SegmentationMasks/combined_gt_stack2.mha,P002_1_FATFRACTION_stack2_dseg.nii.gz,0.876268,5.000000,0.779784,-0.223858,0.211939,0.000027
47,47,P002_1/SegmentationMasks/combined_gt_stack3.mha,P002_1_FATFRACTION_stack3_dseg.nii.gz,0.787232,4.242641,0.649120,-0.414401,0.347886,0.000004
48,48,P003_1/SegmentationMasks/combined_gt_stack1.mha,P003_1_FATFRACTION_stack1_dseg.nii.gz,0.648627,9.165151,0.479977,-0.689569,0.517672,0.000005
49,49,P003_1/SegmentationMasks/combined_gt_stack2.mha,P003_1_FATFRACTION_stack2_dseg.nii.gz,0.764458,5.099020,0.618723,-0.461268,0.378810,0.000007
50,50,P003_1/SegmentationMasks/combined_gt_stack3.mha,P003_1_FATFRACTION_stack3_dseg.nii.gz,0.731580,8.602325,0.576765,-0.533123,0.422388,0.000001
51,51,P004_1/SegmentationMasks/combined_gt_stack1.mha,P004_1_FATFRACTION_stack1_dseg.nii.gz,0.834543,6.164414,0.716065,-0.226875,0.250481,0.000071
52,52,P004_1/SegmentationMasks/combined_gt_stack2.mha,P004_1_FATFRACTION_stack2_dseg.nii.gz,0.823305,4.582576,0.699676,-0.313207,0.288170,0.000024
53,53,P004_1/SegmentationMasks/combined_gt_stack3.mha,P004_1_FATFRACTION_stack3_dseg.nii.gz,0.114050,9.219544,0.060473,-1.771901,0.939527,0.000000